
# Loads default set of integrations. Do not remove.
default_config:

debugpy:

logger:
  default: info
  logs:
    custom_components.jukeaudio_ha: debug
    jukeaudio: debug

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
